sudo: required

services:
  - docker

before install:
  - docker build -t amitgupt82/react-test -f ./cllient/Dockerfile.dev ./client 

script:
  - docker run -e CI=true amitgupt82/react-test npm run test

after_success:
  - docker build -t amitgupt82/multi-client ./client
  - docker build -t amitgupt82/multi-nginx ./nginx
  - docker build -t amitgupt82/multi-server ./server
  - docker build -t amitgupt82/multi-worker ./worker
    
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push amitgupt82/multi-client
  - docker push amitgupt82/multi-nginx
  - docker push amitgupt82/multi-server
  - docker push amitgupt82/multi-worker
