sudo: required

services:
  - docker

before install:
  - docker build -t amitgupt82/react-test -f ./client/Dockerfile.dev ./client 

script:
  - docker run -e CI=true amitgupt82/react-test npm run test

after_success:
  - docker build -t amitgupt82/multi-client ./client
  - docker build -t amitgupt82/multi-nginx ./nginx
  - docker build -t amitgupt82/multi-server ./server
  - docker build -t amitgupt82/multi-worker ./worker
    
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push amitgupt82/multi-client
  - docker push amitgupt82/multi-nginx
  - docker push amitgupt82/multi-server
  - docker push amitgupt82/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-container
  env: MultiContainer-env
  bucket_name: elasticbeanstalk-us-east-2-615800104029
  bucket_path: multi_container
  on:
    branch: master
  access_key_id: $AWS_ACCESSKEY
  secret_access_key: $AWS_SECRETKEY  
